<?php

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function actionlink_dropdown_theme() {
  return [
    'actionlink_dropdown_select' => [
      'render element' => 'element',
    ],
    'actionlink_dropdown_details' => [
      'render element' => 'element',
    ],
    'actionlink_dropdown_details_select' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_actionlink_dropdown_details().
 */
function actionlink_dropdown_preprocess_actionlink_dropdown_details(array &$variables) {
  /** @var \Drupal\actionlink_dropdown\HookHandlers\PreprocessHandlers\PreprocessActionlinkDropdownDetailsHandler $service */
  $service = \Drupal::service('actionlink_dropdown.hook_handlers.preprocess_actionlink_dropdown_details');

  $service->preprocess($variables);
}

/**
 * Implements hook_preprocess_actionlink_dropdown_select().
 */
function actionlink_dropdown_preprocess_actionlink_dropdown_select(array &$variables) {
  /** @var \Drupal\actionlink_dropdown\HookHandlers\PreprocessHandlers\PreprocessActionlinkDropdownSelectHandler $service */
  $service = \Drupal::service('actionlink_dropdown.hook_handlers.preprocess_actionlink_dropdown_select');

  $service->preprocess($variables);
}

/**
 * Implements hook_preprocess_actionlink_dropdown_details_select().
 */
function actionlink_dropdown_preprocess_actionlink_dropdown_details_select(array &$variables) {
  /** @var \Drupal\actionlink_dropdown\HookHandlers\PreprocessHandlers\PreprocessActionlinkDropdownDetailsSelectHandler $service */
  $service = \Drupal::service('actionlink_dropdown.hook_handlers.preprocess_actionlink_dropdown_details_select');

  $service->preprocess($variables);
}
