<?php

declare(strict_types=1);

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function actionlink_dropdown_theme() {
  return [
    'actionlink_dropdown_select' => [
      'render element' => 'element',
    ],
    'actionlink_dropdown_details' => [
      'render element' => 'element',
    ],
    'actionlink_dropdown_details_select' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function actionlink_dropdown_preprocess_actionlink_dropdown_details(array &$variables) {
  $dropdown = $variables['element']['#dropdown'];
  $variables['dropdown'] = [
    '#type' => 'details',
    '#title' => $dropdown['title'],
    '#attributes' => [
      'class' => [
        'button',
        'button-action',
        'button--primary',
        'button--small',
      ],
    ],
    'content' => [
      '#theme' => 'item_list',
      '#type' => 'ul',
      '#items' => array_map(
        function (array $option) use ($dropdown) {
          $url = Url::fromRoute($option['route_name'], $option['route_parameters'] ?? [], $dropdown['localized_options'] ?? []);

          return [
            '#type' => 'link',
            '#title' => $option['title'],
            '#url' => $url,
          ];
        },
        $dropdown['options']
      ),
    ],
  ];

  $variables['add_wrapper'] = empty($variables['element']['#skip_wrapper']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function actionlink_dropdown_preprocess_actionlink_dropdown_select(array &$variables) {
  $dropdown = $variables['element']['#dropdown'];
  $variables['dropdown'] = [
    '#type' => 'select',
    '#options' => ['' => $dropdown['title']],
    '#attributes' => [
      'class' => [
        'button',
        'button-action',
        'button--primary',
        'button--small',
      ],
      'onchange' => 'if(value) window.location.href = value; value = \'\';',
    ],
    '#wrapper_attributes' => [
      'class' => ['actionlink-dropdown-select-container'],
    ],
  ];
  foreach ($dropdown['options'] as $option) {
    $url = Url::fromRoute($option['route_name'], $option['route_parameters'] ?? [], $dropdown['localized_options'] ?? []);

    $variables['dropdown']['#options'][$url->toString()] = $option['title'];
  }

  $variables['add_wrapper'] = empty($variables['element']['#skip_wrapper']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function actionlink_dropdown_preprocess_actionlink_dropdown_details_select(array &$variables) {
  $variables['dropdown'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => [
        'actionlink-dropdown-details-select-container',
      ],
    ],
    'details' => [
      '#theme' => 'actionlink_dropdown_details',
      '#dropdown' => $variables['element']['#dropdown'],
      '#skip_wrapper' => TRUE,
    ],
    'select' => [
      '#theme' => 'actionlink_dropdown_select',
      '#dropdown' => $variables['element']['#dropdown'],
      '#skip_wrapper' => TRUE,
    ],
  ];
}
